# Generated by Django 3.1.4 on 2021-02-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingadress',
            name='order',
        ),
        migrations.AddField(
            model_name='shippingadress',
            name='order',
            field=models.ManyToManyField(to='store.Order'),
        ),
    ]
