# Generated by Django 3.1.4 on 2021-02-09 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210209_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingadress',
            name='order',
        ),
        migrations.AddField(
            model_name='shippingadress',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.order'),
        ),
    ]
