# Generated by Django 3.1.4 on 2021-02-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210209_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('Мужской', 'Мужской'), ('Женский', 'Женский'), ('Детский', 'Детский')], default='man', max_length=30, verbose_name='Пол'),
        ),
    ]
