# Generated by Django 3.1 on 2021-06-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210509_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Страна производства:'),
        ),
        migrations.AddField(
            model_name='product',
            name='madeOf',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Состав'),
        ),
        migrations.AddField(
            model_name='product',
            name='season',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Сезон'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Цвет'),
        ),
    ]
