# Generated by Django 3.1 on 2021-06-02 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210602_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='season',
            field=models.CharField(choices=[('summer', 'Лето'), ('autumn ', 'Осень'), ('winter ', 'Зима'), ('spring  ', 'Весна')], default='man', max_length=30, verbose_name='Сезон'),
        ),
    ]
